# This file was generated by GoReleaser. DO NOT EDIT.
class GitSwitch < Formula
  desc "Switch git users quickly."
  homepage "https://github.com/alfiesal/git-switch"
  version "0.4.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.4.1/git-switch_0.4.1_MacOS_x86_64.tar.gz"
    sha256 "7e46dd1eacb513ef90466b55bc10f5c23cc8d5458a3302a2bd19fb2c654e4744"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.4.1/git-switch_0.4.1_Linux_x86_64.tar.gz"
    sha256 "68000e54289fcffd6ba6aa2b9a8c7cb6b53fb697d8659a8d45eaa8e34842d3dc"
  end

  def install
    bin.install "git-switch"
  end
end
