# This file was generated by GoReleaser. DO NOT EDIT.
class GitSwitch < Formula
  desc "Switch git users quickly."
  homepage "https://github.com/alfiesal/git-switch"
  version "0.4.3"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/alfiesal/git-switch/releases/download/v0.4.3/git-switch_0.4.3_MacOS_x86_64.tar.gz"
    sha256 "fcd67efd0af24235f08243e569a1f394cedc842fe4a2d8cb5498be36d64d6fa9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/alfiesal/git-switch/releases/download/v0.4.3/git-switch_0.4.3_Linux_x86_64.tar.gz"
    sha256 "699f5157c7cd9d4b43610fa338bc41f6f92d84162a30df2c9be9c7863348c45b"
  end

  def install
    bin.install "git-switch"
  end
end
