# This file was generated by GoReleaser. DO NOT EDIT.
class GitSwitch < Formula
  desc "Switch git users quickly."
  homepage "https://github.com/alfiesal/git-switch"
  version "0.4.2"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.4.2/git-switch_0.4.2_MacOS_x86_64.tar.gz"
    sha256 "d6bea00a65386235cc2b589be7de22c59f75a537c70976b5ad05f41c64273e6b"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/<repo_owner>/<repo_name>/releases/download/v0.4.2/git-switch_0.4.2_Linux_x86_64.tar.gz"
    sha256 "3ce633cade6e4eb423627afda98d39d04530b9da6a4baac142e579c641609e38"
  end

  def install
    bin.install "git-switch"
  end
end
